cuda: true
data:
  data_dir: /kaggle/input/python-qa-api-usage/1.0-data-div-ans-sep-api-usage.json
  max_length: 512
  padding: false
  padding_side: right
  split: test
  truncate_promt: true
log_file: /content/test-base-125M.csv
model_name: EleutherAI/gpt-neo-125m
save_steps: 100
seed: 42
test_model_path: null
test_params:
  log_file: /content/test-tuned-api_usage-answer_loss-bredogenerated-125M.csv
  save_steps: 100
  test_model_path: /content/artifacts/model-34980p14:v4/model.ckpt
  use_cache: true
wandb:
  api: text
  args:
    group: reward
    job_type: test
    name: 125M-base-test
  project_name: CQA_RLHF
  table_name: 125M-reward
