cuda: true
data:
  data_dir: /root/CQA_RLHF/data/1.0-data-div-ans-sep-api-usage-with-gen.json
  max_length: 1024
  padding: false
  padding_side: right
  split: test
  truncate_promt: true
model_name: EleutherAI/gpt-neo-125m
save_steps: 100
seed: 42
test_params:
  log_file: /test-tuned-api_usage-125M-1024.csv
  save_steps: 100
  test_model_path: /root/CQA_RLHF/reward_model/mse_regression/CQA_RLHF_v2/30c0m8r9/checkpoints/epoch=16-step=1632.ckpt
  use_cache: true
wandb:
  api: text
  args:
    group: reward
    job_type: test
    name: test-reward-125M-1024
  project_name: CQA_RLHF_v2
  table_name: 125M-reward
