data:
  batch_size: 16
  data_dir: /root/CQA_RLHF/data/1.0-data-div-ans-sep-api-usage-with-gen.json
  max_length: 1024
  on_tpu: false
  truncate_promt: true
model_name: Myashka/125M_GPTneo_reward_base
model_params:
  adam_betas:
  - 0.9
  - 0.99
  do_compute_metrics: true
  learning_rate: 2.0e-05
  use_cache: false
  warmup_steps_per_cent: 0.01
  weight_decay: 0.001
  freeze_emb: true
  freeze_ln: true
  freeze_attn: true
  freeze_ff: true
  freeze_other: true
  layers_not_to_freeze:
  - 0
  - 11
  mae_loss: false
seed: 42
trainer:
  checkpoint:
    dirpath: /kaggle/working/Checkpoints
    every_n_train_steps: 1000
    log_obg: val_accuracy
    mode: max
  ckpt_path: null
  params:
    accelerator: gpu
    accumulate_grad_batches: 1
    gradient_clip_val: 1
    log_every_n_steps: 20
    max_epochs: 20
    num_sanity_val_steps: 2
    overfit_batches: 0
    precision: '16'
    strategy: ddp
    val_check_interval: 435
wandb:
  api: text
  args:
    group: reward
    job_type: train
    name: 125M-lr_2e_5-1_ws-api_usage-16_bs-ddp
  project_name: CQA_RLHF_v2
